#autostart.conf
#exec-once = uwsm-app -- hyprsunset
exec-once = hyprsunset
exec-once = hyprctl dispatch workspace 1
exec-once = nm-online -q -t 30 || sleep 5 && gtk-launch Notion
exec-once = nm-online -q -t 30 || sleep 5 && vesktop
exec-once = nm-online -q -t 30 || sleep 5 && thunderbird
exec-once = nm-online -q -t 30 || sleep 5 && localsend 

#hyprland.conf
workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1

#windowrulev2 = workspace 3 silent,class:^(org.mozilla.Thunderbird)$
#windowrulev2 = workspace 5 silent,class:^(vesktop)$
#windowrulev2 = workspace 5 silent,class:^(chrome-www.notion.so__Developer-Dashboard-21576835374280689041d3d7b48d4e56-Default)$

windowrule = workspace 3 silent, match:class org.mozilla.Thunderbird
windowrule = workspace 5 silent, match:class (?i)vesktop
windowrule = workspace 5 silent, match:class ^chrome-www.notion.so__Developer-Dashboard.*

#looknfeel.conf
general {
    # No gaps between windows or borders
    gaps_in = 3
    gaps_out = 10
    #border_size = 1
    # Use master layout instead of dwindle
    # layout = master
}

#input.conf
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  kb_options = compose:caps # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitivity for mouse/trackpad (default: 0)
  sensitivity = -0.5 

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4

    # Left-click-and-drag with three fingers
    # drag_3fg = 1
  }
}

#monitors.conf
env = GDK_SCALE,1
monitor = DP-1,1920x1080@200,1920x0,1
monitor = HDMI-A-1,1920x1080@60,0x0,1

